# Generated by Django 3.2 on 2023-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_physical_address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('bank_card_number', models.CharField(max_length=19)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=255)),
                ('potential_irrational_purchase', models.BooleanField()),
                ('products_list', models.JSONField()),
                ('english_description', models.JSONField()),
            ],
        ),
    ]
